import { requireAdmin } from "@/lib/admin";
import { getDatabase } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";

const denied = () => NextResponse.json({ error: "Bạn không có quyền quản trị." }, { status: 403 });
export async function GET() { try { await requireAdmin(); return NextResponse.json(getDatabase().prepare("SELECT * FROM Event ORDER BY date DESC").all()); } catch (error) { if (error instanceof Error && error.message === "FORBIDDEN") return denied(); return NextResponse.json({ error: "Không thể tải sự kiện." }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { await requireAdmin(); const b = await request.json(); if (!b.title || !b.description || !b.date || !b.time || !b.location) return NextResponse.json({ error: "Vui lòng nhập đủ thông tin sự kiện." }, { status: 400 }); const id = crypto.randomUUID(); getDatabase().prepare("INSERT INTO Event (id,title,description,date,time,location,capacity,price,image,isPublished) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id,b.title.trim(),b.description.trim(),b.date,b.time,b.location.trim(),b.capacity || "Không giới hạn",b.price || "Miễn phí",b.image || "🎉",b.isPublished === false ? 0 : 1); return NextResponse.json({ id }, { status: 201 }); } catch (error) { if (error instanceof Error && error.message === "FORBIDDEN") return denied(); return NextResponse.json({ error: "Không thể thêm sự kiện." }, { status: 500 }); } }
export async function PATCH(request: NextRequest) { try { await requireAdmin(); const id = request.nextUrl.searchParams.get("id"); const b = await request.json(); if (!id) return NextResponse.json({ error: "Thiếu mã sự kiện." }, { status: 400 }); getDatabase().prepare("UPDATE Event SET title=?,description=?,date=?,time=?,location=?,capacity=?,price=?,image=?,isPublished=? WHERE id=?").run(b.title.trim(),b.description.trim(),b.date,b.time,b.location.trim(),b.capacity,b.price,b.image,b.isPublished ? 1 : 0,id); return NextResponse.json({ message: "Đã cập nhật sự kiện." }); } catch (error) { if (error instanceof Error && error.message === "FORBIDDEN") return denied(); return NextResponse.json({ error: "Không thể cập nhật sự kiện." }, { status: 500 }); } }
export async function DELETE(request: NextRequest) { try { await requireAdmin(); const id = request.nextUrl.searchParams.get("id"); if (!id) return NextResponse.json({ error: "Thiếu mã sự kiện." }, { status: 400 }); getDatabase().prepare("DELETE FROM Event WHERE id=?").run(id); return NextResponse.json({ message: "Đã xóa sự kiện." }); } catch (error) { if (error instanceof Error && error.message === "FORBIDDEN") return denied(); return NextResponse.json({ error: "Không thể xóa sự kiện." }, { status: 500 }); } }
